/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usfirst.frc2421.Neptune.commands;

import edu.wpi.first.wpilibj.can.CANTimeoutException;
import org.usfirst.frc2421.Neptune.Robot;

/**
 *
 * @author Kal
 */
public class collect {
    public boolean on = false;
    
    public collect() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    } 

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() throws CANTimeoutException {
        
        on = !on;
        if(on) {
            Robot.collectionSystem.motor(1.0); }
        else {
            Robot.collectionSystem.motor(0.0); }
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
