// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2421.Neptune.subsystems;

import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2421.Neptune.RobotMap;



/**
 *
 */
public class CollectionSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput opticalSensor = RobotMap.pickupSystemOpticalSensor;
    DigitalInput limitSwitch = RobotMap.pickupSystemLimitSwitch;
    CANJaguar beltMotor = RobotMap.pickupSystemBeltMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public int numOfFrisbees = 0;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    
    public boolean getSwitch()
    {
        return limitSwitch.get();
    }
            
    public boolean getOptic()
    {
        return opticalSensor.get();
    }
    
    public void goMotor() throws CANTimeoutException
    {
        beltMotor.setX(.5);//enter actual motor speed here later
    }
    
    public void stopMotor() throws CANTimeoutException
    {
       beltMotor.setX(0);
    }
    
    public void upFriz()
    {
        numOfFrisbees ++;
    }
    
}

