//FINISHED
// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2421.Neptune.subsystems;

import org.usfirst.frc2421.Neptune.RobotMap;
import org.usfirst.frc2421.Neptune.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ShootSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar wheel1 = RobotMap.shootSystemWheel1;
    CANJaguar wheel2 = RobotMap.shootSystemWheel2;
    Servo angleMotor = RobotMap.shootSystemAngleMotor;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public void startShooter(double speed) {
        try {
            wheel1.setX(-speed);
            wheel2.setX(-speed);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
    }
    public void stopShooter() {
        try {
            wheel1.setX(0);
            wheel2.setX(0);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
    }
    public void clearShooterAngle() {
        angleMotor.setAngle(0);
    }
    public void setShooterAngle(double angle)  {
        angleMotor.setAngle(angle);
    }

    public double checkShooterAngle(){
        return angleMotor.getPosition();
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

