// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2421.Neptune.commands.shoot;

import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2421.Neptune.Robot;

/**
 *
 */
public class AngleManipulation extends Command {

    public AngleManipulation() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shootSystem);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    private double angle;
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.shootSystem.angle = Robot.shootSystem.measureAngleOfFire.getAverageValue() * 72;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        /*double currentAngle = Robot.shooter.checkGyroAngle();
        double targetAngle = 0;
        double angleSeparation = targetAngle - currentAngle;
        double acceptableDifference = .75;
        if(angleSeparation > acceptableDifference){
            try {
                Robot.shooter.shooterAngleIncrease();
            } catch (Exception ex) {
            }
            }
       else if(angleSeparation < acceptableDifference){
            try {
                Robot.shooter.shooterAngleDecrease();
            } catch (CANTimeoutException ex) {
            }
       }
       else{
            try {
                Robot.shooter.stopAngleMotor();
            } catch (Exception ex) {
            }
       }*/
       Robot.shootSystem.angle = Robot.shootSystem.measureAngleOfFire.getAverageValue() * 72;
    }
        
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
